### ISSUE TITLE
Problem with GoogleSheetsImporter using Windows

### ISSUE THREAD

**Issue by TashaHazel** [outfrost/deckswipe#33]
Hi outfrost, there are a few error when I try to run your project in Unity. I already create new API Key at Google Cloud Platform and paste the key at _apiKey variable but it's still not working. Is there any solution that I can use to fix these problems?

![image](https://user-images.githubusercontent.com/39523695/70678227-77616880-1ccc-11ea-9c8c-7b8dbd279c82.png)

**Comment by outfrost** [comment]
There are a few possible issues here.

1. You've posted your API key publicly in the above screenshot. Just so you know, that's not recommended, because other people could abuse your request quota, or even (in extreme cases) get your Google Cloud account suspended for abuses. That's why I deactivated the API key included in this codebase when I stopped paying attention to the project. But it's not a huge deal :)
1. The `NullReferenceException` in `GameProgress.AttachReferences()` is described in #32, with a simple solution provided (just not yet upstreamed).
1. I'm not sure why you would be getting a 403 from Google, as the spreadsheet you're trying to fetch is still publicly viewable. Maybe you haven't enabled the Sheets v3 API for your API key? have a look around the Google Cloud Console.

**Comment by TashaHazel** [comment]
Hi, I am sorry. I do not realized that the API key should not be share in public, thanks for your info! Alright I will try later, thank you for your response :)

**Comment by outfrost** [comment]
Any luck? Should I close this?

**Comment by TashaHazel** [comment]
Yes please.
